version: "3"
services:
  mongodb:
    image: mongo
    expose:
    - "27017"
  stranger-things-api:
    build: .
    expose:
    - "3000"
    environment:
    - PORT=3000
    - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/stranger-things
    depends_on:
    - mongodb
